### ISSUE TITLE
Update source attributes

### ISSUE THREAD

**Issue by blootsvoets** [RADAR-base/ManagementPortal#196]
It would be nice to have a mechanism to re-register sources or at least update their attributes. For example, firmware version, Android version, etc. Right now the pRMT is using the `POST api/subjects/{login}/sources` query, but that will give `409 Conflict` on double posts. I'd expect a `POST api/subjects/{login}/sources/{sourceId}` call that takes a subset of the Source properties and updates those.

There is a `PUT /api/sources` call, but at least the pRMT does not have access to that. Generally, the `PUT` request method is meant to replace a resource, but I only want to update the existing source.

**Comment by nivemaham** [comment]
True. `Source-registration` is considered a one time activity and we have some constraints built on top of it e.g. allowing only one source of a given `source-type` for that subject etc, which results in `409` for double posts. We are using `PUT` for all `update` features in other entities, which includes partial updates. The access to update method can be achieved by changing the scopes for pRMT client. BTW, AFAIR we agreed on sending those meta-data while registration of the source, since they are already known upon registration or we can have another post request. But according to rest conventions, the `POST is to request as a new subordinate of the resource identified by the Request-URI`, so can we have something like `POST api/subjects/{login}/sources/{sourceId}/attributes` or `POST api/subjects/{login}/sources/{sourceId}/meta-data`. Correct me if i am wrong.

**Comment by blootsvoets** [comment]
From https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.5, the definition is as you state. But also that the first use of `POST` is
-  Annotation of existing resources;

If you do `POST api/subjects/{login}/sources/{sourceId}`, you can request a new subordinate (`=attributes`) of the resource identified by the request URI (`=source`). This also does not limit you to only `attributes`, but could also affect the name of a device. Indeed you could also make available a `.../{sourceId}/attributes` URL to reference only the attributes.

Example for an Android Phone: storing the Android version. It remains the same phone but changes the metadata.

**Comment by nivemaham** [comment]
All right. Then both options sounds good to me. If the first option is more generic and could be a good use, we can go as you suggest with `POST api/subjects/{login}/sources/{sourceId}`
