### ISSUE TITLE
Investigate the implementation of Delete subject for project admin authority

### ISSUE THREAD

**Issue by yatharthranjan** [RADAR-base/ManagementPortal#260]
Delete subject is required for project admins if a faulty subject is created and needs to be removed. The possible consequences of deleting a subject should be investigated. If possible what constraints need to be added ?

**Comment by blootsvoets** [comment]
First off: user deletion is irreversible.

There are at least two direct consequences of removing a participant user completely:
1. Metadata attached to a user ID becomes unknown, e.g., external ID, other projects or sources it is assigned to.
2. Data collected for the participant becomes unreferenced in the backend. That means that the data is still there, but it cannot be accessed from the REST API. The data will also still be in the HDFS and CSV storage, but analysts won't be able to connect that data to a person.

Item 1 is an issue if it affects other projects or systems. Item 2 is an issue if the deletion was unintentional, or if a person ever requests its data to be removed from our system as per GDPR, at which time we can no longer find out what data we should delete.

Several mitigations for these issues are possible:
1. Never remove a participant, but assign it a metadata flag for "deleted", or assign a new role ROLE_DELETED_PARTICIPANT. This way, we make deletion reversible and above consequences can be negated.
2. Remove a participant only under the condition that no other projects have ever been assigned to it, nor any sources. That way we are sure that deletion will not affect any other projects and that no data for that participant has yet been collected. This preempts the consequences above.
3. Ask a system administrator to remove the participant. The same consequences remain, but the sysadmin can take further measures to for example record the deleted user credentials offline. Ideally, there is a written procedure for how the sysadmin should act in a user deletion scenario. For example, the sysadmin could also invoke a data deletion script (not yet available), that purges all user data from the MongoDB database, HDFS and CSV storage, or places it in a confined place.

@nivemaham @dennyverbeeck what do you think?

**Comment by nivemaham** [comment]
I agree. I would go for the combination of item 1 and 3, i.e. as a PROJECT_ADMIN a participant can be flagged "deleted" or even the current status as "discontinued" would work.  For PROJECT_ADMINS, we can display only the active participants by default, with a possibility of displaying discontinued participants too with additional filters. 
In addition we should also add the feature for the SYS_ADMIN to delete the participant, which is irreversible and it collectively delete the data associated to the participant as well. This would allow us to have an informed decision about the deletion of subject.

**Comment by afolarin** [comment]
Slightly upstream of this problem, but can we look at making the Redcap Integration more transnational? Perhaps try to avoid the scenario where misconfigured Management Portal users get created (which necessitates their deletion)

**Comment by dennyverbeeck** [comment]
This also ties in to the new auditing mechanism. With Hibernate Envers we will have a full history of all entities. When an entity is deleted (as in effectively deleted from a table), then the audit table will hold a record with state of the entity at deletion, and a flag indicating it was deleted. This will allow us to always track down deleted subjects (and any other deleted entities).

Given that with Envers enabled we will never actually lose data, i think it's safe to keep the actual 'Delete' for the case of faulty subjects, next to the 'Discontinued' which i think has more the semantic of a subject dropping out of the study (correct me if i'm wrong). 

Currently only a SYS_ADMIN can delete subjects. I'm not opposed to extending this to project admins, but now it provides an additional barrier for a project admin, i.e. they need to explicitly ask another human to delete a subject, so less chance of accidental removal.

So i think we should leverage the audit history of entities to go back to deleted subjects if necessary, since that way we don't need to implement additional roles and additional logic to handle these roles in a special way.

PS: I'm aiming at end of this week to finish the Envers implementation and creating a PR for it!

**Comment by blootsvoets** [comment]
Good point! Would this also keep the external ID and human readable identifier? In case those are needed to link a user to a person/study?

**Comment by dennyverbeeck** [comment]
Preview of the audits: in this screenshot we see the global history, where we see the project admin (padmin) creating a subject (the green subject badge), then iteratively modifying it (the yellow badges), and eventually the sys admin comes in to delete the subject (red badge).
![image](https://user-images.githubusercontent.com/10878787/39269071-fcfd9a98-48d1-11e8-9b05-067081c1103e.png)

This screenshot now shows the detail history for the subject that the project admin had created. We can see the creation, then in each modification we can see some changes to the fields of the subject, we can even see a source being assigned. Eventually we see the deletion by the sys admin.
![image](https://user-images.githubusercontent.com/10878787/39269189-78862c66-48d2-11e8-991f-ee3962a95c86.png)

**Comment by dennyverbeeck** [comment]
Closed by #261
