### ISSUE TITLE
Auto-generated source name contains null

### ISSUE THREAD

**Issue by blootsvoets** [RADAR-base/ManagementPortal#269]
https://github.com/RADAR-base/ManagementPortal/blob/e8659760edcce08f8e2aa63775677671bbbd8255/src/main/java/org/radarcns/management/service/SubjectService.java#L280
creates a "unique" source name using eight UUID characters, plus the client-provided device name. However, it uses the source name that has not been generated yet: the default source name only gets added before persisting.

**Comment by nivemaham** [comment]
https://github.com/RADAR-base/ManagementPortal/blob/master/src/main/java/org/radarcns/management/domain/Source.java#L114
From my understanding @PrePersist should be called when the object is created to be saved. 
 My guess would be that the `sourceType.getModel()` returns null and the `String.join()` fails. Will investigate more on this.

**Comment by blootsvoets** [comment]
The String concatenation succeeds but with a `null` second part. In the subjectservice the source is created and then the sourceName is directly queried. That means that PrePersist methods have not yet been called. Perhaps the sourceName can get a default value in the constructor instead?

**Comment by nivemaham** [comment]
You are right. The `PrePersist`haven't been called before we are trying to retrieve the value to assign source name. We cannot have the default value set in default constructor, since the we are also using value from `sourceType` which was not set yet. One solution could be we have an overloaded constructor and pass the sourceType, or we have to update the sourceName after it has been created.

**Comment by nivemaham** [comment]
Fix is pushed here #271
