### ISSUE TITLE
Test production mode in integration test

### ISSUE THREAD

**Issue by blootsvoets** [RADAR-base/ManagementPortal#717]
Currently, we only test ManagementPortal in dev mode in Github actions. This does not test the PostgreSQL integration. Ideally, we add a step to the Github Actions docker job to run the created docker image with docker-compose and test if it functions. A minimal implementation tests if ManagementPortal becomes healthy.

An example would be the first two services in https://github.com/RADAR-base/radar-app-config/blob/master/docker-compose.yml.

**Comment by Bdegraaf1234** [comment]
When do we want to run prod-tests? 

Since currently the prod e2e-tests and dev e2e-tests are identical it seems excessive to run both as part of the `main.yml` workflow. which do we run in main?

For `release.yml` and `pre-release.yml` I suggest we just run both.

Alternatively, we could probably make a profile of which tests to run in prod/dev but I don't think that would be worth it at this point.

**Comment by Bdegraaf1234** [comment]
They run in pre-release now :)
